#!/usr/bin/env python3
"""task_reflect_learn.py

Reflect (Self-Improvement) Certification.

Purpose:
- Query the Shared Brain for recently completed automation tasks.
- Synthesize 'Learnings' or 'Axioms' based on successful runs.
- Update the system state to reflect 'Team IQ' growth.
"""

from __future__ import annotations

import argparse
import sqlite3
import json
import os
from pathlib import Path
from datetime import datetime

from lib import AutomationAgentTask

# Path to the shared brain (Project-level Decentralized Memory)
REPO_ROOT = Path(__file__).resolve().parents[3]
BRAIN_PATH = REPO_ROOT / ".agent" / "working_memory.db"

KNOWLEDGE_PATH = REPO_ROOT / "knowledge" / "team_learnings.md"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", action="store_true")
    args = ap.parse_args()

    task = AutomationAgentTask(
        name="Reflect: Self-Improvement Cycle",
        description="Analyzing recent automation history to extract system patterns."
    )

    if not args.run:
        print("[Reflect] Prepared mode. Use --run.")
        return 0

    task.start()

    # 1. Query the Brain
    def query_brain():
        conn = sqlite3.connect(BRAIN_PATH)
        curr = conn.cursor()
        
        # Get last 10 successful tasks
        curr.execute("SELECT name, description, result FROM automation_tasks WHERE status = 'COMPLETED' ORDER BY finished_at DESC LIMIT 10")
        rows = curr.fetchall()
        
        # Get count per category (clinical, docs, cleanup, etc.)
        curr.execute("SELECT count(*) FROM automation_tasks WHERE status = 'COMPLETED'")
        total_wins = curr.fetchone()[0]
        
        conn.close()
        return {"rows": rows, "total_wins": total_wins}

    data = task.step("Query Shared Brain for Success Patterns", query_brain)
    rows = data["rows"]
    total_wins = data["total_wins"]

    # 2. Synthesize Insights
    def synthesize():
        learnings = []
        # Basic logic: Detect keywords in task names to identify "Unlocked Capabilities"
        capabilities = set()
        for name, desc, res in rows:
            if "Whisper" in name: capabilities.add("Local Speech-to-Text (Offline)")
            if "PDF" in name: capabilities.add("Professional PDF Generation (Pandoc)")
            if "Document" in name: capabilities.add("Multi-Modal Document Parsing")
            if "Desktop" in name: capabilities.add("macOS System Automation (AppleScript/Finder)")
            if "Excel" in name or "Data" in name: capabilities.add("Structured Data Mastery (Excel/Pandas)")
            if "Reflect" in name: capabilities.add("Self-Improvement (Reflection Engine)")
            if "ByteRover" in name: capabilities.add("Context Engineering (Hierarchical Knowledge Tree)")
            if "Dashboard" in name or "Mission Control" in name: capabilities.add("Premium Telemetry UI (Vite/React/Glassmorphism)")
            if "Focus" in name or "Watchdog" in name: capabilities.add("Focus Shield (Interrupt-Free Execution)")
            if "Nexus" in name: capabilities.add("Nexus Link (Inter-Agent Multi-Agent Protocol)")

        insight = {
            "timestamp": datetime.now().isoformat(),
            "unlocked_capabilities": sorted(list(capabilities)),
            "total_successful_missions": total_wins,
            "axiom": "Multi-Agent Coordination + Structured Context = The Best Autonomous Computer."
        }
        return insight

    insights = task.step("Synthesize Team Insights", synthesize)

    # 3. Update Knowledge Artifact
    def update_knowledge():
        KNOWLEDGE_PATH.parent.mkdir(parents=True, exist_ok=True)
        
        content = f"""# 🧠 Team Learnings & Evolution
*Last Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*

## 🚀 Unlocked Capabilities
{chr(10).join([f'- {c}' for c in insights['unlocked_capabilities']])}

## 📊 Mission Stats
- **Total Successful Automations**: {insights['total_successful_missions']}

## 💎 Current Axiom
> {insights['axiom']}

---
*This document is auto-generated by the Reflect skill.*
"""
        KNOWLEDGE_PATH.write_text(content)
        return str(KNOWLEDGE_PATH)

    knowledge_file = task.step("Update Team Knowledge Artifact", update_knowledge)

    task.finish(success=True, final_result={
        "insights": insights,
        "artifact": knowledge_file
    })
    
    print(f"\n[Reflect Success] System has evolved. Newest Axoim: {insights['axiom']}")

if __name__ == "__main__":
    main()
